# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'smc_gui.ui'
#
# Created: Tue Apr 21 14:07:28 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(486, 374)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(-2, -3, 491, 328))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_input = QtGui.QWidget()
        self.tab_input.setObjectName(_fromUtf8("tab_input"))
        self.listWidget_in = QtGui.QListWidget(self.tab_input)
        self.listWidget_in.setGeometry(QtCore.QRect(10, 10, 466, 241))
        self.listWidget_in.setFrameShape(QtGui.QFrame.StyledPanel)
        self.listWidget_in.setFrameShadow(QtGui.QFrame.Sunken)
        self.listWidget_in.setUniformItemSizes(False)
        self.listWidget_in.setObjectName(_fromUtf8("listWidget_in"))
        self.pushButton_add_in = QtGui.QPushButton(self.tab_input)
        self.pushButton_add_in.setGeometry(QtCore.QRect(418, 260, 31, 26))
        self.pushButton_add_in.setFlat(False)
        self.pushButton_add_in.setObjectName(_fromUtf8("pushButton_add_in"))
        self.pushButton_remove_in = QtGui.QPushButton(self.tab_input)
        self.pushButton_remove_in.setGeometry(QtCore.QRect(446, 260, 31, 26))
        self.pushButton_remove_in.setObjectName(_fromUtf8("pushButton_remove_in"))
        self.tabWidget.addTab(self.tab_input, _fromUtf8(""))
        self.tab_output = QtGui.QWidget()
        self.tab_output.setObjectName(_fromUtf8("tab_output"))
        self.pushButton_add_out = QtGui.QPushButton(self.tab_output)
        self.pushButton_add_out.setGeometry(QtCore.QRect(418, 260, 31, 26))
        self.pushButton_add_out.setFlat(False)
        self.pushButton_add_out.setObjectName(_fromUtf8("pushButton_add_out"))
        self.listWidget_out = QtGui.QListWidget(self.tab_output)
        self.listWidget_out.setGeometry(QtCore.QRect(10, 10, 466, 241))
        self.listWidget_out.setFrameShape(QtGui.QFrame.StyledPanel)
        self.listWidget_out.setFrameShadow(QtGui.QFrame.Sunken)
        self.listWidget_out.setUniformItemSizes(False)
        self.listWidget_out.setObjectName(_fromUtf8("listWidget_out"))
        self.pushButton_remove_out = QtGui.QPushButton(self.tab_output)
        self.pushButton_remove_out.setGeometry(QtCore.QRect(446, 260, 31, 26))
        self.pushButton_remove_out.setObjectName(_fromUtf8("pushButton_remove_out"))
        self.tabWidget.addTab(self.tab_output, _fromUtf8(""))
        self.tab_settings = QtGui.QWidget()
        self.tab_settings.setObjectName(_fromUtf8("tab_settings"))
        self.label_enable = QtGui.QLabel(self.tab_settings)
        self.label_enable.setGeometry(QtCore.QRect(18, 18, 161, 18))
        self.label_enable.setObjectName(_fromUtf8("label_enable"))
        self.comboBox_enable = QtGui.QComboBox(self.tab_settings)
        self.comboBox_enable.setGeometry(QtCore.QRect(190, 13, 271, 28))
        self.comboBox_enable.setObjectName(_fromUtf8("comboBox_enable"))
        self.label_root = QtGui.QLabel(self.tab_settings)
        self.label_root.setGeometry(QtCore.QRect(18, 58, 111, 18))
        self.label_root.setObjectName(_fromUtf8("label_root"))
        self.comboBox_root = QtGui.QComboBox(self.tab_settings)
        self.comboBox_root.setGeometry(QtCore.QRect(190, 53, 211, 28))
        self.comboBox_root.setObjectName(_fromUtf8("comboBox_root"))
        self.label_archive = QtGui.QLabel(self.tab_settings)
        self.label_archive.setGeometry(QtCore.QRect(18, 98, 111, 18))
        self.label_archive.setObjectName(_fromUtf8("label_archive"))
        self.comboBox_archive = QtGui.QComboBox(self.tab_settings)
        self.comboBox_archive.setGeometry(QtCore.QRect(190, 93, 271, 28))
        self.comboBox_archive.setObjectName(_fromUtf8("comboBox_archive"))
        self.label_interval = QtGui.QLabel(self.tab_settings)
        self.label_interval.setGeometry(QtCore.QRect(18, 138, 140, 18))
        self.label_interval.setObjectName(_fromUtf8("label_interval"))
        self.spinBox_interval = QtGui.QSpinBox(self.tab_settings)
        self.spinBox_interval.setGeometry(QtCore.QRect(190, 133, 271, 28))
        self.spinBox_interval.setObjectName(_fromUtf8("spinBox_interval"))
        self.label_priority = QtGui.QLabel(self.tab_settings)
        self.label_priority.setGeometry(QtCore.QRect(18, 178, 160, 18))
        self.label_priority.setObjectName(_fromUtf8("label_priority"))
        self.label_dropbox = QtGui.QLabel(self.tab_settings)
        self.label_dropbox.setGeometry(QtCore.QRect(18, 218, 150, 18))
        self.label_dropbox.setObjectName(_fromUtf8("label_dropbox"))
        self.comboBox_dropbox = QtGui.QComboBox(self.tab_settings)
        self.comboBox_dropbox.setGeometry(QtCore.QRect(190, 213, 271, 28))
        self.comboBox_dropbox.setObjectName(_fromUtf8("comboBox_dropbox"))
        self.label_token = QtGui.QLabel(self.tab_settings)
        self.label_token.setGeometry(QtCore.QRect(18, 258, 120, 18))
        self.label_token.setObjectName(_fromUtf8("label_token"))
        self.lineEdit_token = QtGui.QLineEdit(self.tab_settings)
        self.lineEdit_token.setGeometry(QtCore.QRect(190, 253, 271, 28))
        self.lineEdit_token.setObjectName(_fromUtf8("lineEdit_token"))
        self.slider_priority = QtGui.QSlider(self.tab_settings)
        self.slider_priority.setGeometry(QtCore.QRect(190, 173, 271, 31))
        self.slider_priority.setMinimum(0)
        self.slider_priority.setMaximum(19)
        self.slider_priority.setPageStep(10)
        self.slider_priority.setProperty("value", 19)
        self.slider_priority.setSliderPosition(19)
        self.slider_priority.setTracking(True)
        self.slider_priority.setOrientation(QtCore.Qt.Horizontal)
        self.slider_priority.setInvertedAppearance(True)
        self.slider_priority.setInvertedControls(False)
        self.slider_priority.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.slider_priority.setTickInterval(1)
        self.slider_priority.setObjectName(_fromUtf8("slider_priority"))
        self.pushButton_add_root = QtGui.QPushButton(self.tab_settings)
        self.pushButton_add_root.setGeometry(QtCore.QRect(402, 54, 31, 26))
        self.pushButton_add_root.setObjectName(_fromUtf8("pushButton_add_root"))
        self.pushButton_remove_root = QtGui.QPushButton(self.tab_settings)
        self.pushButton_remove_root.setGeometry(QtCore.QRect(430, 54, 31, 26))
        self.pushButton_remove_root.setObjectName(_fromUtf8("pushButton_remove_root"))
        self.tabWidget.addTab(self.tab_settings, _fromUtf8(""))
        self.pushButton_apply = QtGui.QPushButton(Dialog)
        self.pushButton_apply.setGeometry(QtCore.QRect(8, 337, 85, 26))
        self.pushButton_apply.setObjectName(_fromUtf8("pushButton_apply"))
        self.pushButton_close = QtGui.QPushButton(Dialog)
        self.pushButton_close.setGeometry(QtCore.QRect(392, 337, 85, 26))
        self.pushButton_close.setObjectName(_fromUtf8("pushButton_close"))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.comboBox_enable, self.comboBox_root)
        Dialog.setTabOrder(self.comboBox_root, self.comboBox_archive)
        Dialog.setTabOrder(self.comboBox_archive, self.spinBox_interval)
        Dialog.setTabOrder(self.spinBox_interval, self.slider_priority)
        Dialog.setTabOrder(self.slider_priority, self.comboBox_dropbox)
        Dialog.setTabOrder(self.comboBox_dropbox, self.lineEdit_token)
        Dialog.setTabOrder(self.lineEdit_token, self.pushButton_apply)
        Dialog.setTabOrder(self.pushButton_apply, self.pushButton_close)
        Dialog.setTabOrder(self.pushButton_close, self.listWidget_in)
        Dialog.setTabOrder(self.listWidget_in, self.pushButton_add_out)
        Dialog.setTabOrder(self.pushButton_add_out, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.pushButton_remove_in)
        Dialog.setTabOrder(self.pushButton_remove_in, self.listWidget_out)
        Dialog.setTabOrder(self.listWidget_out, self.pushButton_add_in)
        Dialog.setTabOrder(self.pushButton_add_in, self.pushButton_remove_out)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "SaveMyCode!", None))
        self.pushButton_add_in.setText(_translate("Dialog", "+", None))
        self.pushButton_remove_in.setText(_translate("Dialog", "-", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_input), _translate("Dialog", "Input", None))
        self.pushButton_add_out.setText(_translate("Dialog", "+", None))
        self.pushButton_remove_out.setText(_translate("Dialog", "-", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_output), _translate("Dialog", "Output", None))
        self.label_enable.setText(_translate("Dialog", "Enable SaveMyCode!", None))
        self.label_root.setText(_translate("Dialog", "Root directory", None))
        self.label_archive.setText(_translate("Dialog", "Archive format", None))
        self.label_interval.setText(_translate("Dialog", "Check every", None))
        self.spinBox_interval.setSuffix(_translate("Dialog", " mins", None))
        self.label_priority.setText(_translate("Dialog", "Priority", None))
        self.label_dropbox.setText(_translate("Dialog", "Enable DropBox", None))
        self.label_token.setText(_translate("Dialog", "Access token", None))
        self.pushButton_add_root.setText(_translate("Dialog", "+", None))
        self.pushButton_remove_root.setText(_translate("Dialog", "-", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_settings), _translate("Dialog", "Settings", None))
        self.pushButton_apply.setText(_translate("Dialog", "&Apply", None))
        self.pushButton_close.setText(_translate("Dialog", "&Close", None))

